# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='kind',
            field=models.CharField(choices=[('OFFICE', 'Office place'), ('HOME', (('FlAT', 'Flat'), ('HOUSE', 'House'))), ('LAND', 'Land'), ('COMMERCIAL', 'Commercial'), ('UNKNOWN', 'Unknown')], max_length=10),
        ),
    ]
