# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0003_auto_20161017_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarycategory',
            name='main_cat',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='bili_api.MainCategory'),
        ),
    ]
