# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0003_auto_20161022_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ad',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
