# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0004_auto_20161022_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OFFICE', 'Office place'), ('HOME', (('FlAT', 'Flat'), ('HOUSE', 'House'))), ('LAND', 'Land'), ('COMMERCIAL', 'Commercial'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('status', models.CharField(choices=[('RENT', 'Rent'), ('SALE', 'Sale'), ('SHARE', 'Share')], max_length=7)),
                ('no_bed_room', models.IntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='bili_api.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bili_api.MainCategory')),
            ],
        ),
    ]
