# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0004_secondarycategory_main_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='secondarycategory',
            name='main_cat',
        ),
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='SecondaryCategory',
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bili_api.Ad'),
        ),
    ]
