# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0005_maincategory_property_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bili_api.SubCategory'),
        ),
    ]
