# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0007_auto_20161022_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='spotlight',
            field=models.NullBooleanField(),
        ),
    ]
