# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0008_ad_spotlight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='active_since',
            new_name='active_from',
        ),
        migrations.AddField(
            model_name='property',
            name='payment',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='PAYMENT_CHOICES.MONTHLY', max_length=7),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='bili_api.Person'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='bili_api.Person'),
        ),
    ]
