# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0008_auto_20161020_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to='ads'),
        ),
    ]
