# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0009_auto_20161025_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='payment',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='Monthly', max_length=7),
        ),
    ]
