# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0009_auto_20161020_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
