# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0010_auto_20161025_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bili_api.Ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='bili_api.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
        migrations.AlterField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bili_api.Ad'),
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('user', 'ad')]),
        ),
    ]
