# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 13:29
from __future__ import unicode_literals

import bili_api.models.ads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili_api', '0010_auto_20161020_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to=bili_api.models.ads.AdImage.user_directory_path),
        ),
    ]
